name: photutils

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - jupyter
    - matplotlib
    - numpy
    - scikit-image
    - scipy
    - docutils <0.13.1
    - Sphinx >=1.5.1