name: photutils

channels:
    - astropy

dependencies:
    - python>=3
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - scikit-image
    - scikit-learn
    - docutils
    - Sphinx
    - nomkl